### ISSUE TITLE
Make font rendering look nicer

### ISSUE THREAD

**Issue by kghose** [kghose/groho#23]
Current settings (997d2ba4554) seem not optimal for rendered text:

<img width="185" alt="screen shot 2018-07-22 at 6 22 19 pm" src="https://user-images.githubusercontent.com/664644/43050751-39998260-8ddc-11e8-9f8e-c4991aa549a3.png">

<img width="123" alt="screen shot 2018-07-22 at 5 27 00 pm" src="https://user-images.githubusercontent.com/664644/43050753-412da4de-8ddc-11e8-91f0-22c08b1bb73b.png">

<img width="148" alt="screen shot 2018-07-22 at 5 27 12 pm" src="https://user-images.githubusercontent.com/664644/43050757-49dd693e-8ddc-11e8-9803-62b58d070909.png">

**Comment by kghose** [comment]
Hints from @mosra 

There are these options to help you with antialiasing:

- if the generated glyph cache is too big compared to rendered text, you will get very sharp pixelated edges because of downsampling
- if the generated glyph cache is too small compared to rendered text, you will get blurry and aliased edges because of upsampling
- with non-distance-field text one thing that's usually done is supersampling the text two times (so e.g. if you render text at 16pt, you make the glyph cache 32pt) ... note this is different from MSAA, which supersamples only edges. That's what I am doing in the Ui library (in case you are using it)
- in case of distance field glyph cache, there is the radius parameter when generating, affecting how much you can zoom the text without losing much quality
- there is also the smoothness parameter when rendering, which balances between sharp (but pixelated) and smooth (but blurry) ... and this needs to be tuned based on how large your text is on the screen, what's the input font size and what's the glyph cache scaling ratio and calculation radius

**Comment by mosra** [comment]
From the screenshots it looks like the smoothness parameter (when rendering) is too small, causing such jaggies. If you try to enable HiDPI it could get a bit better, but that's not the root cause.
